미션 확인 부탁드립니다!
YGwan/spring-is-coming pull request #2
Opened 2023-03-17 14:57 UTC by YGwan

1. Exception 처리
2. spring jdbc 회원가입 구현
3. spring jdbc 로그인 구현
4. spring jdbc jwt 생성 및 유효성 검사 로직 구현

2023-03-18 04:50 UTC, ecsimsw requested changes

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +            );
targetValue는 단일값인데 Where key = value로 하지 않고 IN을 사용한 이유가 궁금합니다!
또 exists를 사용할 수도 있겠네요! IN과 성능 차이도 공부해보세요.

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +    public String validLogIn(LogInRequest request) {
valid는 형용사로 '유효한 로그인'을 메서드명으로 의도한게 맞으신가요?
만약 그렇다면 다른 개발자들은 '유효한 로그인'이라는 동작의 반환으로 어떤 것을 기대할까요?

저라면 true, false로 유효한지가 반환될 것을 기대할 것 같아요. 
아니면 로그인 요청이 유효한지 확인한다 라는 의미로 'validateLoginRequest'을 메서드 명으로 하고 리턴 타입을 void로 할 것 같네요.

validLogin의 반환이 로그인 요청의 유저 이름인지는 예상하기 어려울 것 같아요.

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +        return ResponseEntity.badRequest().body(e.toString());
어떤 객체든 가급적 toString보다는 따로 정의된 메시지를 출력하려고 노력해보세요.
exception.toString보다는 exception.getMessage() 등으로요.

DBException을 따로 빼서 관리한다는 생각은 참 좋아요.
근데 DBException의 정보를 바로 응답해도 될까요?

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/MyAdvice.java
> +    }
UserController에서 ControllerAdvice를 따로 빼신 이유가 있을까요?

제가 ControllerAdvice를 사용해보라고 했던 의도는 UserController의 관심사 밖, 프로젝트 공통 범위의 예외들을 처리하는데 사용될 수 있다 는 것을 보여주고 싶었습니다. 예를 들면 프로젝트 전체 범위에서 예외 처리되지 않은 IllegalArgumentException의 처리 방법을 정의할 수 있겠네요. UserException에 대한 핸들링은 UserController에서 해도 되지 않았을까 하는데 뺴신 이유가 궁금합니다.

추가로 프로젝트 전체 범위의 NullPointerException을 단순히 BadRequest라고 생각해도 될까요?
서버단의 NPE라면 500번대를 반환해야하지 않을까요?

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +    private final JwtProvider jwtProvider;
JwtProvider는 Bean으로 등록하신 이유가 있을까요?
Dao의 RowMapper처럼 필드에서 생성했어도 충분했을것 같은데 Bean으로 등록했던 이유가 있을지 궁금하네요. 
참고한 코드가 Bean으로 등록했던게 이유라면 본인의 근거를 생각해보세요!

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +    }
User와 Person이 헷갈려요...
어떤 기준인거죠?

아예 다른 프로젝트라고 들었던거 같은데 막상 컨트롤러는 UserController, signUp은 Person이니 너무 헷갈리네요. 
Person은 그저 요청 매핑을 위한 dto인가요?

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +    public ResponseEntity<?> emailHandler() {
더 좋은 메서드명이 있을 것 같습니다.
emailHandler는 MethodArgumentNotValidException을 처리하는 예외 핸들러로 생각되지 않네요.

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +        return new ResponseEntity<>("올바른 형식의 이메일 주소여야 합니다.", HttpStatus.BAD_REQUEST);
모든 MethodArgumentNotValidException의 이유가 '올바른 형식의 이메일 주소가 아닌 경우' 인가요?

예를 들면 User 조건이 까다로워져 '올바른 형식의 비밀번호가 아닌 경우'도 MethodArgumentNotValidException으로 잡아야한다면 어떻게 수정되어야할까요.

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +    public String addUser(Person person) {
역시나 User나 Person의 개념이 헷갈리네요.
둘이 어떤 차이가 있나요?

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +
줄간격 확인

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/service/MyPageService.java
> +public class MyPageService {
MyPageService도 마찬가지네요.
UserService랑 어떤 차이가 있는거지요?

insertUser가 똑같이 있는데 인자가 다르다니!!!

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/service/MyPageService.java
> +        validAge(person.getAge());
이렇게 getter로 코드가 전개되면 객체/도메인의 역할은 아무것도 없고 Service코드에서 getter로 꺼낸 값들을 절차지향으로 풀이하는 것 밖에 안됩니다.
지금으론 도메인은 단순히 데이터 덩어리, 모든 로직은 Service에서 절차지향으로 처리되겠네요.

가능하면 객체의 동작을 만들려고 노력해보세요. 예를들면 password과 rePassword가 다름은 person에서 잡아도 충분하지 않을까요? 데이터를 getter로 가져와서 Service단에서 검사하지 않아도 될 것 같아요.

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +    public String createToken(String username, String email) {
아하 token에 들어가는 정보가 username이랑 email이었군요!!!
드디어 풀리는 미스테리.

2023-03-18 04:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +    public String validateToken(String token) {
문자열로 함수의 결과를 알려주는 것은 별로네요. validateToken 함수의 응답으로 다른 개발자는 어떤 것을 기대할 것 같나요?
그게 어떤 것이든 "올바른 토큰입니다."를 기대하는 사람은 없을거예요. 

```
if(validateToken(token).equals("올바른 토큰입니다.")) {
  // 토큰이 올바른 경우의 로직
}
```
이 함수를 그대로 사용하려면 위처럼 유효함을 확인해야할텐데 괜찮은 방식일까요? 물론 '예외를 잘 터트렸으니 예외가 안터지면 유효한거야' 라고 말할 수 있을 것도 같습니다. 그런 생각이라면 void로 반환하면 어떨까요? 
"올바른 토큰입니다."를 반환하는 것은 아무런 의미를 갖지 못하는 것 같네요.

2023-03-19 06:18 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +
확인 후 수정했습니다!!
제대로 확인하고 이런 실수 줄이겠습니다!!

2023-03-19 06:23 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +    public String validLogIn(LogInRequest request) {
마자요 이 부분을 고민을 좀 많이 했습니다.
어짜피 조건에 맞지 않으면 에러를 발생시키기 때문에 굳이 해당 변수들이 올바른지에 대한 체크에 return값이 필요없다고 생각했었습니다. 리턴값이 생기면 이를 또 추가적으로 처리해야할 불필요한 코드 줄이 생긴다고 생각했기 때문입니다.
그래서 리턴값을 void로 설정한 뒤 함수명을 어떤식으로 작성할까에 대한 고민을 했었는데 valid는 확실히 return이 boolean값이라고 생각할 거 같다는 생각이 들었습니다. 이를 valid가 아닌 validate로 하면 좀 더 자연스럽군요!!

따라서 void를 리턴하는 모든 변수 체크 로직 함수를 validate형식의 함수명으로 변경하였습니다.

2023-03-19 06:31 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +            );
생각해보니 저는 해당 조건값이 결과가 존재하는지를 확인하는 로직이니깐 굳이 IN을 사용하지 않고 '='를 사용해서 처리하는 것이 더 좋겟네요!! 그리고 만약 '='를 사용하지 않는다고 해도 IN보다는 EXISTS를 사용하는 것이 더 효율적이겠네요!!

EXISTS는 조건에 해당하는 ROW의 존재 유무와 체크 후 더이상 수행하지 않지만 IN의 경우 조건에 해당하는 ROW의 컬럼을 비교하여 체크한다. 즉 EXISTS은 SELECT 절을 평가하지 않으므로 일반적으로 IN에 비해 성능이 좋습니다.
또한,
EXISTS : 메인 쿼리의 결과값을 서브 쿼리에 대입하여 조건 비교 후 결과를 출력한다. ( 메인쿼리 -> EXISTS 쿼리 )
IN : 서브 쿼리의 결과값을 메인 쿼리에 대입하여 조건 비교 후 결과를 출력한다. ( IN쿼리 -> 메인 쿼리 )

2023-03-19 06:41 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/UserController.java
> +        return ResponseEntity.badRequest().body(e.toString());
DBException을 사용한 이유가 DB에서 생긴 에러를 바로 응답하지 않기 위해서 처리한거라 그러한 형식은 잘못 되었다고 생각합니다.
해당 부분을 PageControllerAdvice로 따로 빼서 이 부분에서 해당 부분을 "에러가 발생하였습니다." 의 형식으로 반환하도록 변경하였습니다.

2023-03-19 06:42 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +
죄송합니다!!
이 부분도 수정해서 바로 적용하였습니다.
이러한 실수는 신경써서 줄이도록 노력하겠습니다!

2023-03-19 06:46 UTC, YGwan commented on src/main/java/com/example/springMVC/service/MyPageService.java
> +public class MyPageService {
이 부분 DB를 합치면서 insertUser는 하나만 살리고 나머지 하나는 제거하였습니다.
또한 Service코드도 PersonService를 UserService에 합쳐 하나의 서비스와 DB로 동작하도록 수정하였습니다.

두개의 프로젝트를 분리해 처리해야하는 줄 알고 나눴는데 저도 할때 결국 Person DB가 User DB 역할을 한다고 생각했습니다.!!
이번기회에 두개의 DB를 합쳐보면서 초반에 설계를 잘못하면 후에 수정할때 매우 힘들다는 것을 느꼈습니다.
저같은 경우 entity 나 service가 별로 없어서 비교적 금방 했지만, 만약 실제 회사나 대규모 프로젝트에서 이런 상황이 온다면,
사실상 고치기가 매우 힘들 것 같다는 생각이 들었습니다. 다음부터는 제대로 이해하고 설계를 한 후 개발을 하도록 하겠습니다!

2023-03-19 08:35 UTC, YGwan commented on src/main/java/com/example/springMVC/service/MyPageService.java
> +        validAge(person.getAge());
일단 오케이.

2023-03-19 08:38 UTC, YGwan commented on src/main/java/com/example/springMVC/service/MyPageService.java
> +        validAge(person.getAge());
password repassword 동일 처리 로직 변경

2023-03-20 06:02 UTC, YGwan commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +    public String validateToken(String token) {
이 부분은 임시 로직이였고 최종 코드에서는 해당 작업이 boolean값을 반환하여 유효한 토큰일 경우 값을 처리하는 로직을 추가로 작성하였습니다.

2023-03-20 06:03 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/MyAdvice.java
> +public class MyAdvice {
해당 명은 GlobalControllerAdvice로 변경하였습니다.

2023-03-20 06:20 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/UserController.java
> +        String jwtToken = jwtProvider.createToken(request.getUsername(), myPageService.logIn(request));
해당 부분 함수명은 createTokenByUsername으로 변경하였고
logIn의 경우 logIn결과로 email을 뱉는 것은 잘못된거 같고 Token발급을 위해 추가적인 DAO작업을 수행하는 것 또한
불필요한 작업일 것 같아 토큰에 payLoad에 사용되는 값은 Username으로만 한정하였습니다.

2023-03-20 08:22 UTC, ecsimsw requested changes
잘하고 있다~!!!!

2023-03-20 08:22 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/GlobalControllerAdvice.java
> +public class GlobalControllerAdvice {
GlobalControllerAdvice, unhandledExceptionHandler 은 한번 더 복습해보시고 더 좋은 방식을 계속 고민해보기.

2023-03-20 08:22 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +    }
토큰 테스트용 API 제거 부탁드립니다.

2023-03-20 08:22 UTC, ecsimsw commented on src/main/java/com/example/springMVC/dao/UserDao.java
> +            throw new UserException(targetColumn + " 이 중복되었습니다.");
테스트 해보기.
1. 회원 가입 API로 ("김진환", "01012341234")을 가입시킨 후
2. 다시 가입 API로 ("박용관", "01012341234") 가입 요청을 보내면 

어떤 에러 메시지가 나오는지 확인합니다. 그리고 그 응답 코드와 메시지가 서비스 보안 정책에 옳게 응답되는지 확인합니다.
(번호 중복에 대한 정책이 없었다면 중복 컬럼을 email로 바꿔서 진행해보세요.)

2023-03-20 08:22 UTC, ecsimsw commented on src/main/java/com/example/springMVC/entity/User.java
> +    @Email(message = "이메일 fcuck")
!!!!

2023-03-20 15:17 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/PersonDao.java
> +    public String validLogIn(LogInRequest request) {
아 이 부분 변경하고 커밋이 안되있었군요!! 
이 부분은 이제 boolean을 뱉기 때문에 validToken으로 수정했습니다!!

2023-03-21 00:50 UTC, ecsimsw commented on src/main/java/com/example/springMVC/service/MyPageService.java
> +public class MyPageService {
너무 좋은 경험과 후기네요.

2023-03-21 00:55 UTC, ecsimsw commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +    public String validateToken(String token) {
좋네요!!!
다음부턴 임시 로직, 테스트는 리뷰 요청 전에 제거하던가 수정하는걸로 연습해볼까요?

지금까진 학습의 의미가 강한 코드라고 생각해서 남겨뒀을 수도 있을거 같은데, 이제부턴 진짜 다른 팀원에게 리뷰를 요청한다는 마음으로 해보면 꼼꼼하게 코드 확인하는 연습에 더 도움될거 같아요.

2023-03-21 04:40 UTC, YGwan commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
jjwt-api는 토큰 생성을 위한 객체들을 추상화 하기 위한 라이브러리이고 

jjwt-impl는 JJWT 라이브러리의 구현을 가리킨다. 이 종속성을 Java 프로젝트로 가져오면 JJWT 라이브러리에서 제공하는 클래스 및 메서드에 액세스하여 JWT를 사용할 수 있습니다

하지만 jjwt-jackson의 경우 JWT의 JSON 직렬화 및 역직렬화를 처리하기 위해 JJWT(Java JWT)와 함께 자주 사용되는 또 다른 종속성이다.
JJWT를 사용하여 JWT를 만들거나 구문 분석하면 토큰을 나타내는 JSON 문자열이 생성됩니다. 그러나 JJWT는 이 JSON 문자열을 자바 객체로 변환하는 내장 메커니즘을 제공하지 않는다. 그것이 jjwt-jackson 필요한 이유이다.

이번 미션에서는 JSON 문자열을 자바 객체로 변환할 필요가 없기 때문에 jjwt-jackson의 종속성 추가는 불필요한 것으로 판단해 해당 부분을 제거하였고 추가적으로 나머지 두 종속성을 최신 버전으로 업데이트 했습니다.

2023-03-21 04:43 UTC, YGwan commented on src/main/java/com/example/springMVC/entity/User.java
> +    @Email(message = "이메일 fcuck")
이 부분 제거 완료 했습니다!!

2023-03-21 05:20 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/UserController.java
> +        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
이 부분 아래와 마찬가지로 통일성을 줘서 ResponseEntity.badRequest().body(e.getMessage()); 이렇게 처리하였습니다.

2023-03-21 05:38 UTC, YGwan commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
그런데 jjwt-jackson의 종속성을 추가하지 않고 실행했을때 실행은 원활하게 됐는데 실제 jwt를 생성하는 과정에서 에러가 발생하는 것을 확인했습니다. 따라서 최종적으로 해당 종속성을 다시 추가하니 문제 없이 돌아가는 것을 확인했습니다.
이 결과 제가 생각하기에는 3가지의 종속성이 다 필요하다고 생각하는데 혹시 어떤것을 뺄 수 있는지 궁금합니다!!

2023-03-21 05:38 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/GlobalControllerAdvice.java
> +        e.printStackTrace();
알겠습니다!!
로그 관리 부분에 대해서도 이후에 공부해보도록 하겠습니다. 감사합니다!!

2023-03-21 05:40 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/UserController.java
> +        return ResponseEntity.status(410).body(e.getMessage());
이 부분         return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(e.getMessage());
이러한 형식으로 변경하였습니다!!

2023-03-21 05:47 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/UserDao.java
> +                "SELECT PASSWORD FROM USER WHERE USERNAME IN (?)",
public void validateLogIn(LogInRequest request) {
        try {
            jdbcTemplate.queryForObject(
                    "SELECT ID FROM USER WHERE USERNAME = ? AND PASSWORD = ?",
                    Long.class,
                    request.getUsername(), request.getPassword()
            );

        } catch (EmptyResultDataAccessException e) {
            throw new DBException("로그인 실패");
        }
    }

이런식으로 처리하면 한번에 처리가 가능하겠군요!!
확인하고 수정하였습니다!!

2023-03-21 06:18 UTC, YGwan commented on src/main/java/com/example/springMVC/dao/UserDao.java
> +            throw new UserException(targetColumn + " 이 중복되었습니다.");
bad request(400 error)랑 이메일이 중복되었다는 에러가 발생합니다.

검색 결과 409 (현재 서버의 상태와 충돌했을 때 사용한다. 정확한 정의는 존재하지 않지만, 닉네임이나 아이디 중복의 경우 이미 서버에 존재하는 리소스(닉네임/아이디)와 충돌해서 발생하는 중복 에러를 다루기도 한다.) 에러를 발생시키는 것이 맞다고 생각했습니다.
저같은 경우 이렇게 중복되었을때 UserException을 발생시키고, 이를 한번에 ExceptionHandler로 처리하고 있는대 만약 다른 형태의 http응답코드를 받기 위해서 다른 에러 클래스를 정의해서 따로 처리하는 것이 좋을지 아니면 지금 이렇게 UserException으로 처리하는게 좋을지 고민이 됩니다. 혹시 요즘 트렌드가 있는지 궁금합니다!

2023-03-21 06:21 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/GlobalControllerAdvice.java
> +    }
1번의 경우 GlobalControllerAdvice 클래스에서 처리를 하기 때문에 조회 결과가 존재하지 않습니다. 라는 에러 문구와 함께 400 에러를 발생시킵니다.

2번의 경우 이 경우 DBException을 발생시키기 때문에 DB 에러가 발생하였습니다.  라는 에러 문구와 함께 400 에러를 발생시킵니다.

2023-03-21 22:50 UTC, ecsimsw commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
아하!!! 좋네요~
항상 의존성을 꼭 추가해야하는지, 이유를 반드시 확인해보라는 의도였습니다!! 
```
implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation

implementation 'org.springframework.boot:spring-boot-starter-validation'
```
도 다른 의존성과 형식을 맞추면 더 좋겠네요.

2023-03-21 23:11 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/GlobalControllerAdvice.java
> +    }
오 딱 좋은 테스트였네요!!

DB 에러를 직접 응답하는 것보다 1번은 '존재하지 않는 유저입니다', 2번도 '존재하지 않는 유저입니다' 또는 보안상 이 조차 숨기고 싶다면 '로그인 실패' 으로 반환하는게 어떨까요?

로그인시 사용자가 입력한 username이 존재하지 않는 경우 '사용자의 요청'에 문제가 있다고 말해주는 것이 'DB 에러가 발생'했다고 말해주는 것보다 더 낫지 않을까요?

2023-03-21 23:24 UTC, ecsimsw commented on src/main/java/com/example/springMVC/dao/UserDao.java
> +            throw new UserException(targetColumn + " 이 중복되었습니다.");
`https://blog.outsider.ne.kr/1121`
제가 되게 좋아하는 블로그인데 이 문제로 포스팅이 있네요!! ㅎㅎ

사실 이 부분은 정책에 대한 피드백이었습니다. 
"이메일이 중복되었다"라고 응답이 되진 않을까라고 예상했는데 역시 좋은 테스트였네요.

저라면 회원가입에서 컬럼 중복과 중복된 컬럼을 응답하지 않을 것 같습니다. 이렇게 되는 경우 특정 username이 존재하는지, 또는 01012341234를 갖고 있는 번호가 이 서비스에 가입했는지를 금방 알 수 있어서요. 
이 부분은 이게 정답이야 보다는, 이런 것도 고민해보면 좋겠다 싶어서 피드백 남겨봅니다.

2023-03-21 23:27 UTC, ecsimsw commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    private static final Key key = Keys.secretKeyFor(SignatureAlgorithm.HS256);
힌트 `https://github.com/jwtk/jjwt#jws-key-hmacsha`

2023-03-22 02:43 UTC, ecsimsw requested changes

2023-03-22 02:43 UTC, ecsimsw commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +            return true;
테스트 해볼 것 

1. 유저 생성 (진환, 01012341234)
2. 유저 생성 (용관, 01043214321)
3. 유저 로그인 (진환으로) -> 토큰 값 복사
4. 유저 휴대폰 번호 변경 (용관으로) -> 이때 헤더에는 4번에서 복사한 '진환'의 토큰을 사용한다.

이 테스트가 성공해야하는지, 실패해야하는지 고민해보시고 의도한 결과가 아니라면 이를 수정하세요.

2023-03-22 02:43 UTC, ecsimsw commented on src/main/java/com/example/springMVC/service/UserService.java
> +        if (age < 20) {
미션의 정책은 age가 19세 미만인 경우!!

```
age가 19세 미만인 경우 "서비스 정책에 맞지 않는 사용자 나이입니다"를 사용자에게 반환하세요.
```

2023-03-22 04:21 UTC, YGwan commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +    public String validateToken(String token) {
네넵!! 이제부터는 확실히 프로젝트에서 제가 짠 코드를 팀원에게 리뷰를 요청한다는 생각으로 코드를 작성하고 커밋하는 연습을 해보도록 하겠습니다!!

2023-03-22 04:25 UTC, YGwan commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
아 맞아요!! 이 부분 보면서 저번에 말씀해주신게 생각났습니다.
원래는 위에 형식꼴로 했는데 이제는 위보다는 아래 형식으로 코드를 작성한다는 말을 해주셨던게 생각났습니다.

그런데 저번에 했을때는 위의 형식으로 하고 코드를 실행했을때 컴파일 이후 warnning으로 해당 코드는 구 버전이고 신 버전은 "~~~~"하다 라는 문구를 보고 이러한 형식으로 바꿔서 처리했던 걸로 기억하는데 이번 같은 경우에는 그러한 경고가 뜨지 않더라구요!!
그래서 그냥 남겼었는대, 아래와 같은 형식이 있으면 통일성을 주는 것이 더 좋겠네요!!

2023-03-22 04:27 UTC, YGwan commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
해당 코드 아래와 같은 형식으로 변경하였습니다! 이번 기회에 jwt에 필요한 의존성 종류와 함께 어떤식으로 쓰이는지 잘 알게 되었습니다!

2023-03-22 04:55 UTC, YGwan commented on src/main/java/com/example/springMVC/service/UserService.java
> +        if (age < 20) {
아 이 부분 실수 했네요...
19세 미만으로 변경하여 코드 수정 완료했습니다.!!

2023-03-28 13:41 UTC, YGwan commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    private static final Key key = Keys.secretKeyFor(SignatureAlgorithm.HS256);
data 패키지 안 Data 클래스에서 secretString 값을 생성하고 해당 부분은 보호되어야하기 때문에 gitignore를 통해 올리지 않았습니다.
이 값을 getter로 가져와서 인코딩한 값을 key값으로 사용해 jwt를 생성하였습니다.

2023-03-28 14:40 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/GlobalControllerAdvice.java
> +    }
해당 부분 1번 - 존재하지 않는 유저입니다.
2번 - 로그인 실패
로 에러 처리하게끔 로직 변경 하였습니다.

2023-03-30 03:53 UTC, ecsimsw requested changes
굳
진짜 고생많았습니다.

한번씩 쓱 훝어보고 머지하세요 ㅎㅎ
최고십니다.

2023-03-30 03:53 UTC, ecsimsw commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    private static final SecretKey secretKey = Keys.hmacShaKeyFor(secretString.getBytes(StandardCharsets.UTF_8));
SecretKey를 다른 클래스로 빼는 것도 괜찮았겠네요.
```
private static final SecretKey secretKey = Data.getSecretKey();
```
로하면 Keys.hmacShaKeyFor(secretString.getBytes(StandardCharsets.UTF_8))으로 키 인코딩을 그쪽으로 넘길 수 있었겠네요. String으로 굳이 중간 타입을 둔 느낌?
그래도 지금도 좋습니다.

2023-03-30 03:53 UTC, ecsimsw commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    }
필요한 메서드인가요? 
secretString과 secretKey 가 있는 클래스에서 getKey()는 둘 중 어떤걸 반환하는걸 더 기대할까요?

2023-03-30 03:53 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/GlobalControllerAdvice.java
> +    }
확인 완료!!~ 고생했습니다.

2023-03-30 03:53 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/UserController.java
> +    public ResponseEntity<UpdatePhoneNumberResponse> updatePhoneNumber(HttpServletRequest httpServletRequest, @RequestBody UpdatePhoneNumberRequest request) {
@RequestHeader 를 쓸 수 도 있겠네요?
HttpServletRequest와 UpdatePhoneNumberRequest가 파라미터인데 각각의 명이 httpServletRequest, request인게 헷갈려서 좀 더 명화가 할 순 없나 고민해봤습니다.

2023-03-30 03:53 UTC, ecsimsw commented on src/main/java/com/example/springMVC/token/JwtProvider.java
> +            return true;
굳

2023-03-30 04:23 UTC, YGwan commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    }
key값을 확인하기 위해 필요했었는데 해당 클래스에서는 secretKey가 반환되길 기대하겠군요!!
해당 함수명을 getSecretKey()로 바꾸고 return을 secretKey로 변경하였습니다.
key값을 저같은 경우 main에서 실행할때 확인하는 용도가 필요해 getter를 썻지만 사실 그런 용도가 아니라면 필요하진 않은 메서드 같습니다!

2023-03-30 04:32 UTC, YGwan commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    private static final SecretKey secretKey = Keys.hmacShaKeyFor(secretString.getBytes(StandardCharsets.UTF_8));
원래는 key encoding되기 전 값을 출력하기 위해서 위와 같은 형태로 작업했었는데 아래의 리뷰와 함께 생각해보니 불필요한 작업이라는 생각이 들었습니다. 따라서

`private static final SecretKey secretKey = Data.getSecretKey();`


이러한 형식으로 바꿨습니다. 이렇게 하는게 헐씬 좋겠네요!!

2023-03-30 04:33 UTC, ecsimsw commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    }
오홍 근데 이제 Data에서 secret key를 꺼내오는거 아니었나요?
이걸 실행할 때 다시 확인할 필요가 있는지 궁금하네요.

2023-03-30 04:33 UTC, ecsimsw commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    private static final SecretKey secretKey = Keys.hmacShaKeyFor(secretString.getBytes(StandardCharsets.UTF_8));
좋습니다.

2023-03-30 04:35 UTC, YGwan commented on src/main/java/com/example/springMVC/config/SecurityConfig.java
> +    }
아 맞는 말씀이네요!!! 어짜피 제가 정해논 값으로 key가 설정되니 굳이 확인하는 작업이 필요 없겟네요!!
제거하겠습니다!!!

2023-03-30 04:36 UTC, ecsimsw requested changes

2023-03-30 04:36 UTC, ecsimsw commented on src/main/java/com/example/springMVC/controller/AdminController.java
여기 두칸 띄어진거 같으네요!

2023-03-30 04:56 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/UserController.java
> +    public ResponseEntity<UpdatePhoneNumberResponse> updatePhoneNumber(HttpServletRequest httpServletRequest, @RequestBody UpdatePhoneNumberRequest request) {
```
 @PutMapping("/phoneNumber")
    public ResponseEntity<UpdatePhoneNumberResponse> updatePhoneNumber(@RequestHeader("Authorization") String token, @RequestBody UpdatePhoneNumberRequest request)
```

이러한 형식으로 변경하였습니다!! 코드가 한결 깔끔해져서 헐씬 좋은거 같아요!!

2023-03-30 04:56 UTC, YGwan commented on src/main/java/com/example/springMVC/controller/AdminController.java
수정했습니다!!

2023-03-30 06:42 UTC, ecsimsw approved these changes
고생많으셨습니다~

2023-03-30 13:53 UTC, merged